# Generated by Django 3.0.5 on 2020-11-05 10:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0002_auto_20201104_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 8, 10, 16, 29, 354490)),
        ),
        migrations.AlterField(
            model_name='product',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 5, 10, 16, 29, 354490)),
        ),
    ]
