# Generated by Django 3.0.5 on 2020-11-04 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(default='', max_length=60, primary_key=True, serialize=False)),
                ('user_pwd', models.CharField(default='', max_length=60)),
                ('user_name', models.CharField(default='', max_length=60)),
                ('join_date', models.DateField(auto_now_add=True)),
                ('credit', models.IntegerField(default=0)),
            ],
        ),
    ]
